name: Print message

on: 
  push:
    branches:
      -main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shambhavi210/custom-actions-demo@main
        with:
          message: "hello world!"
    
